user             nginx;
worker_processes auto;

error_log /var/log/nginx/error.log notice;
pid       /var/run/nginx.pid;

load_module modules/ngx_otel_module.so;

events {
    worker_connections 1024;
    multi_accept       on;
    use                epoll;
}

http {
    include      /etc/nginx/mime.types;
    default_type application/octet-stream;

    autoindex_localtime on;

    log_format main '$remote_addr - $remote_user [$time_local] "$request" ' '$status $body_bytes_sent "$http_referer" ' '"$http_user_agent" "$http_x_forwarded_for"';

    log_format timed '$remote_addr - $remote_user [$time_local] "$request" ' '$status $body_bytes_sent "$http_referer" ' '"$http_user_agent" ' 'request_time=$request_time ' 'upstream_connect_time=$upstream_connect_time ' 'upstream_header_time=$upstream_header_time ' 'upstream_response_time=$upstream_response_time ' 'upstream_addr=$upstream_addr';

    map $status $log_level {
        # Спец-коды nginx, которые обычно не критичны
        444 "info";   # nginx сам закрыл соединение
        499 "info";   # клиент закрыл соединение

        # Информационные ответы (в т.ч. 101 Switching Protocols)
        ~^1 "info";   # 1xx

        # Успешные и редиректы
        ~^[23] "info";   # 2xx, 3xx

        # Ошибки клиента
        ~^4 "warn";   # 4xx

        # Ошибки сервера
        ~^5 "error";  # 5xx

        # На всякий случай — всё непредвиденное
        default  "error";
    }

    log_format main_json escape=json '{' '"request_method": "$request_method", ' # request method
    '"request_uri": "$request_uri", ' # full path and arguments if the request
    '"body_bytes_sent": "$body_bytes_sent", ' # the number of body bytes exclude headers sent to a client
    '"http_referer": "$http_referer", ' # HTTP referer
    '"http_user_agent": "$http_user_agent", ' # user agent
    '"http_x_forwarded_for": "$http_x_forwarded_for", ' # http_x_forwarded_for
    '"remote_addr": "$remote_addr", ' # client IP
    '"request_id": "$request_id", ' # the unique request id
    '"request_time": "$request_time", ' # request processing time in seconds with msec resolution
    '"status": "$status", ' # response status code
    '"time": "$time_iso8601", ' # local time in the ISO 8601 standard format
    '"level": "$log_level", '
    '"upstream": "$upstream_addr", ' # upstream backend server for proxied requests
    '"upstream_cache_status": "$upstream_cache_status", ' # cache HIT/MISS where applicable
    '"upstream_connect_time": "$upstream_connect_time", ' # upstream handshake time incl. TLS
    '"upstream_header_time": "$upstream_header_time", ' # time spent receiving upstream headers
    '"upstream_response_length": "$upstream_response_length", ' # upstream response length
    '"upstream_response_time": "$upstream_response_time", ' # time spend receiving upstream body
    '"trace_id": "$otel_trace_id"' '}';

    access_log /dev/stdout main_json;
    error_log  /dev/stderr;

    sendfile on;
    #tcp_nopush     on;

    keepalive_timeout 65;

    #gzip  on;

    include /etc/nginx/conf.d/*.conf;
}
