<?php

namespace Modules\SportSectionsWidget\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SportSectionsWidgetOdDatasetsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = array(
            0 =>
                [
                    'id' => 1,
                    'url' => 'https://data.admhmao.ru/api/data/?id=2791462',
                    'data_type' => 'json',
                    'class_handler' => 'Modules\\SportSectionsWidget\\OpenDataHandlers\\OrganisationsSourceHandler',
                    'description' => 'Спортивные организации Кондинского района',
                    'need_update' => 0,
                    'is_active' => 1,
                    'current_hash' => null,
                    'last_update' => null,
                    'dataset_type_id' => 1,
                    'municipality_id' => 1,
                ],
            1 =>
                [
                    'id' => 2,
                    'url' => 'https://data.admhmao.ru/api/data/?id=2791612',
                    'data_type' => 'json',
                    'class_handler' => 'Modules\\SportSectionsWidget\\OpenDataHandlers\\Trainers\\KondinskySourceHandler',
                    'description' => 'Спортивные тренеры Кондинского района',
                    'need_update' => 0,
                    'is_active' => 1,
                    'current_hash' => null,
                    'last_update' => null,
                    'dataset_type_id' => 2,
                    'municipality_id' => 1,
                ],
            2 =>
                [
                    'id' => 3,
                    'url' => 'https://data.admhmao.ru/api/data/?id=2791542',
                    'data_type' => 'json',
                    'class_handler' => 'Modules\\SportSectionsWidget\\OpenDataHandlers\\SectionsSourceHandler',
                    'description' => 'Спортивные секции Кондинского района',
                    'need_update' => 0,
                    'is_active' => 1,
                    'current_hash' => null,
                    'last_update' => null,
                    'dataset_type_id' => 3,
                    'municipality_id' => 1,
                ],
            3 =>
                [
                    'id' => 4,
                    'url' => 'https://data.admhmao.ru/api/data/?id=2792821',
                    'data_type' => 'json',
                    'class_handler' => 'Modules\\SportSectionsWidget\\OpenDataHandlers\\OrganisationsSourceHandler',
                    'description' => 'Спортивные организации Белоярского района',
                    'need_update' => 0,
                    'is_active' => 1,
                    'current_hash' => null,
                    'last_update' => null,
                    'dataset_type_id' => 1,
                    'municipality_id' => 2,
                ],
            4 =>
                [
                    'id' => 5,
                    'url' => 'https://data.admhmao.ru/api/data/?id=2792885',
                    'data_type' => 'json',
                    'class_handler' => 'Modules\\SportSectionsWidget\\OpenDataHandlers\\TrainersSourceHandler',
                    'description' => 'Спортивные тренеры Белоярского района',
                    'need_update' => 0,
                    'is_active' => 1,
                    'current_hash' => null,
                    'last_update' => null,
                    'dataset_type_id' => 2,
                    'municipality_id' => 2,
                ],
            5 =>
                [
                    'id' => 6,
                    'url' => 'https://data.admhmao.ru/api/data/?id=2792839',
                    'data_type' => 'json',
                    'class_handler' => 'Modules\\SportSectionsWidget\\OpenDataHandlers\\SectionsSourceHandler',
                    'description' => 'Спортивные секции Белоярского района',
                    'need_update' => 0,
                    'is_active' => 1,
                    'current_hash' => null,
                    'last_update' => null,
                    'dataset_type_id' => 3,
                    'municipality_id' => 2,
                ],
            6 =>
                [
                    'id' => 7,
                    'url' => 'https://data.admhmao.ru/api/data/?id=2773768',
                    'data_type' => 'json',
                    'class_handler' => 'Modules\\SportSectionsWidget\\OpenDataHandlers\\OrganisationsSourceHandler',
                    'description' => 'Спортивные организации Берёзовского района',
                    'need_update' => 0,
                    'is_active' => 1,
                    'current_hash' => null,
                    'last_update' => null,
                    'dataset_type_id' => 1,
                    'municipality_id' => 3,
                ],
            7 =>
                [
                    'id' => 8,
                    'url' => 'https://data.admhmao.ru/api/data/?id=2788179',
                    'data_type' => 'json',
                    'class_handler' => 'Modules\\SportSectionsWidget\\OpenDataHandlers\\Trainers\\BerezovskySourceHandler',
                    'description' => 'Спортивные тренеры Берёзовского района',
                    'need_update' => 0,
                    'is_active' => 1,
                    'current_hash' => null,
                    'last_update' => null,
                    'dataset_type_id' => 2,
                    'municipality_id' => 3,
                ],
            8 =>
                [
                    'id' => 9,
                    'url' => 'https://data.admhmao.ru/api/data/?id=2788111',
                    'data_type' => 'json',
                    'class_handler' => 'Modules\\SportSectionsWidget\\OpenDataHandlers\\SectionsSourceHandler',
                    'description' => 'Спортивные секции Берёзовского района',
                    'need_update' => 0,
                    'is_active' => 1,
                    'current_hash' => null,
                    'last_update' => null,
                    'dataset_type_id' => 3,
                    'municipality_id' => 3,
                ],
            9 =>
                [
                    'id' => 10,
                    'url' => 'https://data.admhmao.ru/api/data/?id=3237795',
                    'data_type' => 'json',
                    'class_handler' => 'Modules\\SportSectionsWidget\\OpenDataHandlers\\OrganisationsSourceHandler',
                    'description' => 'Спортивные организации г. Лангепас',
                    'need_update' => 0,
                    'is_active' => 1,
                    'current_hash' => null,
                    'last_update' => null,
                    'dataset_type_id' => 1,
                    'municipality_id' => 4,
                ],
            10 =>
                [
                    'id' => 11,
                    'url' => 'https://data.admhmao.ru/api/data/?id=3237873',
                    'data_type' => 'json',
                    'class_handler' => 'Modules\\SportSectionsWidget\\OpenDataHandlers\\Trainers\\LangepasSourceHandler',
                    'description' => 'Спортивные тренеры г. Лангепас',
                    'need_update' => 0,
                    'is_active' => 1,
                    'current_hash' => null,
                    'last_update' => null,
                    'dataset_type_id' => 2,
                    'municipality_id' => 4,
                ],
            11 =>
                [
                    'id' => 12,
                    'url' => 'https://data.admhmao.ru/api/data/?id=3268686',
                    'data_type' => 'json',
                    'class_handler' => 'Modules\\SportSectionsWidget\\OpenDataHandlers\\SectionsSourceHandler',
                    'description' => 'Спортивные секции г. Лангепас',
                    'need_update' => 0,
                    'is_active' => 1,
                    'current_hash' => null,
                    'last_update' => null,
                    'dataset_type_id' => 3,
                    'municipality_id' => 4,
                ],
            12 =>
                [
                    'id' => 13,
                    'url' => 'https://data.admhmao.ru/api/data/?id=2777021',
                    'data_type' => 'json',
                    'class_handler' => 'Modules\\SportSectionsWidget\\OpenDataHandlers\\OrganisationsSourceHandler',
                    'description' => 'Спортивные организации г. Мегион',
                    'need_update' => 0,
                    'is_active' => 0,
                    'current_hash' => null,
                    'last_update' => null,
                    'dataset_type_id' => 1,
                    'municipality_id' => 5,
                ],
            13 =>
                [
                    'id' => 14,
                    'url' => 'https://data.admhmao.ru/api/data/?id=2776965',
                    'data_type' => 'json',
                    'class_handler' => 'Modules\\SportSectionsWidget\\OpenDataHandlers\\Trainers\\MegionSourceHandler',
                    'description' => 'Спортивные тренеры г. Мегион',
                    'need_update' => 0,
                    'is_active' => 0,
                    'current_hash' => null,
                    'last_update' => null,
                    'dataset_type_id' => 2,
                    'municipality_id' => 5,
                ],
            14 =>
                [
                    //Вместо ID (ИНН) - лежит строка с названием
                    'id' => 15,
                    'url' => 'https://data.admhmao.ru/api/data/?id=2776974',
                    'data_type' => 'json',
                    'class_handler' => 'Modules\\SportSectionsWidget\\OpenDataHandlers\\SectionsSourceHandler',
                    'description' => 'Спортивные секции г. Мегион',
                    'need_update' => 0,
                    'is_active' => 0,
                    'current_hash' => null,
                    'last_update' => null,
                    'dataset_type_id' => 3,
                    'municipality_id' => 5,
                ],
            15 =>
                [
                    'id' => 16,
                    'url' => 'https://data.admhmao.ru/api/data/?id=2790411',
                    'data_type' => 'json',
                    'class_handler' => 'Modules\\SportSectionsWidget\\OpenDataHandlers\\OrganisationsSourceHandler',
                    'description' => 'Спортивные организации г. Покачи',
                    'need_update' => 0,
                    'is_active' => 1,
                    'current_hash' => null,
                    'last_update' => null,
                    'dataset_type_id' => 1,
                    'municipality_id' => 6,
                ],
            16 =>
                [
                    'id' => 17,
                    'url' => 'https://data.admhmao.ru/api/data/?id=2791998',
                    'data_type' => 'json',
                    'class_handler' => 'Modules\\SportSectionsWidget\\OpenDataHandlers\\Trainers\\PokachiSourceHandler',
                    'description' => 'Спортивные тренеры г. Покачи',
                    'need_update' => 0,
                    'is_active' => 1,
                    'current_hash' => null,
                    'last_update' => null,
                    'dataset_type_id' => 2,
                    'municipality_id' => 6,
                ],
            17 =>
                [
                    'id' => 18,
                    'url' => 'https://data.admhmao.ru/api/data/?id=2790576',
                    'data_type' => 'json',
                    'class_handler' => 'Modules\\SportSectionsWidget\\OpenDataHandlers\\SectionsSourceHandler',
                    'description' => 'Спортивные секции г. Покачи',
                    'need_update' => 0,
                    'is_active' => 1,
                    'current_hash' => null,
                    'last_update' => null,
                    'dataset_type_id' => 3,
                    'municipality_id' => 6,
                ],
            18 =>
                [
                    'id' => 19,
                    'url' => 'https://data.admhmao.ru/api/data/?id=3374789',
                    'data_type' => 'json',
                    'class_handler' => 'Modules\\SportSectionsWidget\\OpenDataHandlers\\OrganisationsSourceHandler',
                    'description' => 'Спортивные организации г. Пыть-Ях',
                    'need_update' => 0,
                    'is_active' => 1,
                    'current_hash' => null,
                    'last_update' => null,
                    'dataset_type_id' => 1,
                    'municipality_id' => 7,
                ],
            19 =>
                [
                    'id' => 20,
                    'url' => 'https://data.admhmao.ru/api/data/?id=3374682',
                    'data_type' => 'json',
                    'class_handler' => 'Modules\\SportSectionsWidget\\OpenDataHandlers\\Trainers\\PytYakhSourceHandler',
                    'description' => 'Спортивные тренеры г. Пыть-Ях',
                    'need_update' => 0,
                    'is_active' => 1,
                    'current_hash' => null,
                    'last_update' => null,
                    'dataset_type_id' => 2,
                    'municipality_id' => 7,
                ],
            20 =>
                [
                    'id' => 21,
                    'url' => 'https://data.admhmao.ru/api/data/?id=3374798',
                    'data_type' => 'json',
                    'class_handler' => 'Modules\\SportSectionsWidget\\OpenDataHandlers\\SectionsSourceHandler',
                    'description' => 'Спортивные секции г. Пыть-Ях',
                    'need_update' => 0,
                    'is_active' => 1,
                    'current_hash' => null,
                    'last_update' => null,
                    'dataset_type_id' => 3,
                    'municipality_id' => 7,
                ],
            21 =>
                [
                    'id' => 22,
                    'url' => 'https://data.admhmao.ru/api/data/?id=5019964',
                    'data_type' => 'json',
                    'class_handler' => 'Modules\\SportSectionsWidget\\OpenDataHandlers\\Organisations\\RaduzhnySourceHandler',
                    'description' => 'Спортивные организации г. Радужный',
                    'need_update' => 0,
                    'is_active' => 1,
                    'current_hash' => null,
                    'last_update' => null,
                    'dataset_type_id' => 1,
                    'municipality_id' => 8,
                ],
            22 =>
                [
                    'id' => 23,
                    'url' => 'https://data.admhmao.ru/api/data/?id=3069212',
                    'data_type' => 'json',
                    'class_handler' => 'Modules\\SportSectionsWidget\\OpenDataHandlers\\Trainers\\RaduzhnySourceHandler',
                    'description' => 'Спортивные тренеры г. Радужный',
                    'need_update' => 0,
                    'is_active' => 1,
                    'current_hash' => null,
                    'last_update' => null,
                    'dataset_type_id' => 2,
                    'municipality_id' => 8,
                ],
            23 =>
                [
                    'id' => 24,
                    'url' => 'https://data.admhmao.ru/api/data/?id=3069193',
                    'data_type' => 'json',
                    'class_handler' => 'Modules\\SportSectionsWidget\\OpenDataHandlers\\SectionsSourceHandler',
                    'description' => 'Спортивные секции г. Радужный',
                    'need_update' => 0,
                    'is_active' => 1,
                    'current_hash' => null,
                    'last_update' => null,
                    'dataset_type_id' => 3,
                    'municipality_id' => 8,
                ],
            24 =>
                [
                    'id' => 25,
                    'url' => 'https://data.admhmao.ru/api/data/?id=2808001',
                    'data_type' => 'json',
                    'class_handler' => 'Modules\\SportSectionsWidget\\OpenDataHandlers\\OrganisationsSourceHandler',
                    'description' => 'Спортивные организации г. Сургут',
                    'need_update' => 0,
                    'is_active' => 1,
                    'current_hash' => null,
                    'last_update' => null,
                    'dataset_type_id' => 1,
                    'municipality_id' => 9,
                ],
            25 =>
                [
                    'id' => 26,
                    'url' => 'https://data.admhmao.ru/api/data/?id=2808071',
                    'data_type' => 'json',
                    'class_handler' => 'Modules\\SportSectionsWidget\\OpenDataHandlers\\TrainersSourceHandler',
                    'description' => 'Спортивные тренеры г. Сургут',
                    'need_update' => 0,
                    'is_active' => 1,
                    'current_hash' => null,
                    'last_update' => null,
                    'dataset_type_id' => 2,
                    'municipality_id' => 9,
                ],
            26 =>
                [
                    'id' => 27,
                    'url' => 'https://data.admhmao.ru/api/data/?id=2808031',
                    'data_type' => 'json',
                    'class_handler' => 'Modules\\SportSectionsWidget\\OpenDataHandlers\\SectionsSourceHandler',
                    'description' => 'Спортивные секции г. Сургут',
                    'need_update' => 0,
                    'is_active' => 1,
                    'current_hash' => null,
                    'last_update' => null,
                    'dataset_type_id' => 3,
                    'municipality_id' => 9,
                ],
            27 =>
                [
                    'id' => 28,
                    'url' => 'https://data.admhmao.ru/api/data/?id=2977291',
                    'data_type' => 'json',
                    'class_handler' => 'Modules\\SportSectionsWidget\\OpenDataHandlers\\OrganisationsSourceHandler',
                    'description' => 'Спортивные организации г. Урай',
                    'need_update' => 0,
                    'is_active' => 1,
                    'current_hash' => null,
                    'last_update' => null,
                    'dataset_type_id' => 1,
                    'municipality_id' => 10,
                ],
            28 =>
                [
                    'id' => 29,
                    'url' => 'https://data.admhmao.ru/api/data/?id=2987879',
                    'data_type' => 'json',
                    'class_handler' => '',
                    'description' => '(хз откуда взялся этот датасет)Спортивные тренеры г. Урай',
                    'need_update' => 0,
                    'is_active' => 0,
                    'current_hash' => null,
                    'last_update' => null,
                    'dataset_type_id' => 2,
                    'municipality_id' => 10,
                ],
            29 =>
                [
                    'id' => 30,
                    'url' => 'https://data.admhmao.ru/api/data/?id=2987817',
                    'data_type' => 'json',
                    'class_handler' => 'Modules\\SportSectionsWidget\\OpenDataHandlers\\Trainers\\UraySourceHandler',
                    'description' => 'Спортивные тренеры и секции с расписанием г. Урай',
                    'need_update' => 0,
                    'is_active' => 1,
                    'current_hash' => null,
                    'last_update' => null,
                    'dataset_type_id' => 3,
                    'municipality_id' => 10,
                ],
            30 =>
                [
                    'id' => 31,
                    'url' => 'https://data.admhmao.ru/api/data/?id=8156721',
                    'data_type' => 'json',
                    'class_handler' => 'Modules\\SportSectionsWidget\\OpenDataHandlers\\Organisations\\HantyMansiyskSourceHandler',
                    'description' => 'Спортивные организации г. Ханты-Мансийск',
                    'need_update' => 0,
                    'is_active' => 1,
                    'current_hash' => null,
                    'last_update' => null,
                    'dataset_type_id' => 1,
                    'municipality_id' => 11,
                ],
            31 =>
                [
                    'id' => 32,
                    'url' => 'https://data.admhmao.ru/api/data/?id=2790254',
                    'data_type' => 'json',
                    'class_handler' => 'Modules\\SportSectionsWidget\\OpenDataHandlers\\Trainers\\HantyMansiyskSourceHandler',
                    'description' => 'Спортивные тренеры г. Ханты-Мансийск',
                    'need_update' => 0,
                    'is_active' => 1,
                    'current_hash' => null,
                    'last_update' => null,
                    'dataset_type_id' => 2,
                    'municipality_id' => 11,
                ],
            32 =>
                [
                    'id' => 33,
                    'url' => 'https://data.admhmao.ru/api/data/?id=5423089',
                    'data_type' => 'json',
                    'class_handler' => 'Modules\\SportSectionsWidget\\OpenDataHandlers\\Sections\\HantyMansiyskSourceHandler',
                    'description' => 'Спортивные секции г. Ханты-Мансийск',
                    'need_update' => 0,
                    'is_active' => 1,
                    'current_hash' => null,
                    'last_update' => null,
                    'dataset_type_id' => 3,
                    'municipality_id' => 11,
                ],
            33 =>
                [
                    'id' => 34,
                    'url' => 'https://data.admhmao.ru/api/data/?id=2733544',
                    'data_type' => 'json',
                    'class_handler' => 'Modules\\SportSectionsWidget\\OpenDataHandlers\\OrganisationsSourceHandler',
                    'description' => 'Спортивные организации г. Югорск',
                    'need_update' => 0,
                    'is_active' => 1,
                    'current_hash' => null,
                    'last_update' => null,
                    'dataset_type_id' => 1,
                    'municipality_id' => 12,
                ],
            34 =>
                [
                    'id' => 35,
                    'url' => 'https://data.admhmao.ru/api/data/?id=2733552',
                    'data_type' => 'json',
                    'class_handler' => 'Modules\\SportSectionsWidget\\OpenDataHandlers\\Trainers\\UgorskSourceHandler',
                    'description' => 'Спортивные тренеры г. Югорск',
                    'need_update' => 0,
                    'is_active' => 1,
                    'current_hash' => null,
                    'last_update' => null,
                    'dataset_type_id' => 2,
                    'municipality_id' => 12,
                ],
            35 =>
                [
                    'id' => 36,
                    'url' => 'https://data.admhmao.ru/api/data/?id=2733518',
                    'data_type' => 'json',
                    'class_handler' => 'Modules\\SportSectionsWidget\\OpenDataHandlers\\SectionsSourceHandler',
                    'description' => 'Спортивные секции г. Югорск',
                    'need_update' => 0,
                    'is_active' => 1,
                    'current_hash' => null,
                    'last_update' => null,
                    'dataset_type_id' => 3,
                    'municipality_id' => 12,
                ],
            36 =>
                [
                    'id' => 37,
                    'url' => 'https://data.admhmao.ru/api/data/?id=3083052',
                    'data_type' => 'json',
                    'class_handler' => 'Modules\\SportSectionsWidget\\OpenDataHandlers\\OrganisationsSourceHandler',
                    'description' => 'Спортивные организации Нижневартовского района',
                    'need_update' => 0,
                    'is_active' => 1,
                    'current_hash' => null,
                    'last_update' => null,
                    'dataset_type_id' => 1,
                    'municipality_id' => 13,
                ],
            37 =>
                [
                    'id' => 38,
                    'url' => 'https://data.admhmao.ru/api/data/?id=7452924',
                    'data_type' => 'json',
                    'class_handler' => 'Modules\\SportSectionsWidget\\OpenDataHandlers\\Trainers\\NizhnevartovskDistrictSourceHandler',
                    'description' => 'Спортивные тренеры Нижневартовского района',
                    'need_update' => 0,
                    'is_active' => 1,
                    'current_hash' => null,
                    'last_update' => null,
                    'dataset_type_id' => 2,
                    'municipality_id' => 13,
                ],
            38 =>
                [
                    'id' => 39,
                    'url' => 'https://data.admhmao.ru/api/data/?id=3083097',
                    'data_type' => 'json',
                    'class_handler' => 'Modules\\SportSectionsWidget\\OpenDataHandlers\\SectionsSourceHandler',
                    'description' => 'Спортивные секции Нижневартовского района',
                    'need_update' => 0,
                    'is_active' => 1,
                    'current_hash' => null,
                    'last_update' => null,
                    'dataset_type_id' => 3,
                    'municipality_id' => 13,
                ],
            39 =>
                [
                    'id' => 40,
                    'url' => 'https://data.admhmao.ru/api/data/?id=2789450',
                    'data_type' => 'json',
                    'class_handler' => 'Modules\\SportSectionsWidget\\OpenDataHandlers\\OrganisationsSourceHandler',
                    'description' => 'Спортивные организации Октябрьского района',
                    'need_update' => 0,
                    'is_active' => 1,
                    'current_hash' => null,
                    'last_update' => null,
                    'dataset_type_id' => 1,
                    'municipality_id' => 14,
                ],
            40 =>
                [
                    'id' => 41,
                    'url' => 'https://data.admhmao.ru/api/data/?id=2789457',
                    'data_type' => 'json',
                    'class_handler' => 'Modules\\SportSectionsWidget\\OpenDataHandlers\\Trainers\\OktyabrskyDistrictSourceHandler',
                    'description' => 'Спортивные тренеры Октябрьского района',
                    'need_update' => 0,
                    'is_active' => 1,
                    'current_hash' => null,
                    'last_update' => null,
                    'dataset_type_id' => 2,
                    'municipality_id' => 14,
                ],
            41 =>
                [
                    'id' => 42,
                    'url' => 'https://data.admhmao.ru/api/data/?id=5347688',
                    'data_type' => 'json',
                    'class_handler' => 'Modules\\SportSectionsWidget\\OpenDataHandlers\\SectionsSourceHandler',
                    'description' => 'Спортивные секции Октябрьского района',
                    'need_update' => 0,
                    'is_active' => 1,
                    'current_hash' => null,
                    'last_update' => null,
                    'dataset_type_id' => 3,
                    'municipality_id' => 14,
                ],
            42 =>
                [
                    'id' => 43,
                    'url' => 'https://data.admhmao.ru/api/data/?id=2783135',
                    'data_type' => 'json',
                    'class_handler' => 'Modules\\SportSectionsWidget\\OpenDataHandlers\\OrganisationsSourceHandler',
                    'description' => 'Спортивные организации Ханты-Мансийского района',
                    'need_update' => 0,
                    'is_active' => 1,
                    'current_hash' => null,
                    'last_update' => null,
                    'dataset_type_id' => 1,
                    'municipality_id' => 15,
                ],
            43 =>
                [
                    'id' => 44,
                    'url' => 'https://data.admhmao.ru/api/data/?id=2783185',
                    'data_type' => 'json',
                    'class_handler' => 'Modules\\SportSectionsWidget\\OpenDataHandlers\\Trainers\\HantyMansiyskDistrictSourceHandler',
                    'description' => 'Спортивные тренеры Ханты-Мансийского района',
                    'need_update' => 0,
                    'is_active' => 1,
                    'current_hash' => null,
                    'last_update' => null,
                    'dataset_type_id' => 2,
                    'municipality_id' => 15,
                ],
            44 =>
                [
                    'id' => 45,
                    'url' => 'https://data.admhmao.ru/api/data/?id=2783142',
                    'data_type' => 'json',
                    'class_handler' => 'Modules\\SportSectionsWidget\\OpenDataHandlers\\SectionsSourceHandler',
                    'description' => 'Спортивные тренеры Ханты-Мансийского района',
                    'need_update' => 0,
                    'is_active' => 1,
                    'current_hash' => null,
                    'last_update' => null,
                    'dataset_type_id' => 3,
                    'municipality_id' => 15,
                ],
            45 =>
                [
                    'id' => 46,
                    'url' => 'https://data.n-vartovsk.ru/api/v1/8603032896-uchsport/data?api_key=%20APP-VIKA_admhmao.ru&rows=500',
                    'data_type' => 'json',
                    'class_handler' => 'Modules\\SportSectionsWidget\\OpenDataHandlers\\Organisations\\NizhnevartovskSourceHandler',
                    'description' => 'Спортивные организации г. Нижневартовск',
                    'need_update' => 0,
                    'is_active' => 1,
                    'current_hash' => null,
                    'last_update' => null,
                    'dataset_type_id' => 1,
                    'municipality_id' => 16,
                ],
            46 =>
                [
                    'id' => 47,
                    'url' => 'https://data.n-vartovsk.ru/api/v1/8603032896-uchsporttrainers/data?api_key=%20APP-VIKA_admhmao.ru&rows=500',
                    'data_type' => 'json',
                    'class_handler' => 'Modules\\SportSectionsWidget\\OpenDataHandlers\\Trainers\\NizhnevartovskSourceHandler',
                    'description' => 'Спортивные тренеры и секции без расписания г. Нижневартовск',
                    'need_update' => 0,
                    'is_active' => 1,
                    'current_hash' => null,
                    'last_update' => null,
                    'dataset_type_id' => 2,
                    'municipality_id' => 16,
                ],
            47 =>
                [
                    'id' => 48,
                    'url' => 'https://data.admhmao.ru/api/data/?id=2099893',
                    'data_type' => 'json',
                    'class_handler' => 'Modules\\SportSectionsWidget\\OpenDataHandlers\\OrganisationsSourceHandler',
                    'description' => 'Спортивные организации г. Советский',
                    'need_update' => 0,
                    'is_active' => 1,
                    'current_hash' => null,
                    'last_update' => null,
                    'dataset_type_id' => 1,
                    'municipality_id' => 17,
                ],
            48 =>
                [
                    'id' => 49,
                    'url' => 'https://data.admhmao.ru/api/data/?id=2976945',
                    'data_type' => 'json',
                    'class_handler' => 'Modules\\SportSectionsWidget\\OpenDataHandlers\\Trainers\\SovetskySourceHandler',
                    'description' => 'Спортивные тренеры г. Советский',
                    'need_update' => 0,
                    'is_active' => 1,
                    'current_hash' => null,
                    'last_update' => null,
                    'dataset_type_id' => 2,
                    'municipality_id' => 17,
                ],
            49 =>
                [
                    'id' => 50,
                    'url' => 'https://data.admhmao.ru/api/data/?id=2977012',
                    'data_type' => 'json',
                    'class_handler' => 'Modules\\SportSectionsWidget\\OpenDataHandlers\\SectionsSourceHandler',
                    'description' => 'Спортивные секции г. Советский',
                    'need_update' => 0,
                    'is_active' => 1,
                    'current_hash' => null,
                    'last_update' => null,
                    'dataset_type_id' => 3,
                    'municipality_id' => 17,
                ],
            50 =>
                [
                    'id' => 51,
                    'url' => 'https://data.admhmao.ru/api/data/?id=1558825',
                    'data_type' => 'json',
                    'class_handler' => 'Modules\\SportSectionsWidget\\OpenDataHandlers\\Organisations\\SurgutDistrictSourceHandler',
                    'description' => 'Спортивные организации Сургутского района',
                    'need_update' => 0,
                    'is_active' => 1,
                    'current_hash' => null,
                    'last_update' => null,
                    'dataset_type_id' => 1,
                    'municipality_id' => 18,
                ],
            51 =>
                [
                    'id' => 52,
                    'url' => 'https://data.admhmao.ru/api/data/?id=3506574',
                    'data_type' => 'json',
                    'class_handler' => 'Modules\\SportSectionsWidget\\OpenDataHandlers\\Trainers\\SurgutDistrictSourceHandler',
                    'description' => 'Спортивные секции и тренеры с расписанием Сургутского района',
                    'need_update' => 0,
                    'is_active' => 1,
                    'current_hash' => null,
                    'last_update' => null,
                    'dataset_type_id' => 2,
                    'municipality_id' => 18,
                ],
            52 =>
                [
                    'id' => 53,
                    'url' => 'https://data.admhmao.ru/api/data/?id=1206693',
                    'data_type' => 'json',
                    'class_handler' => 'Modules\\SportSectionsWidget\\OpenDataHandlers\\OrganisationsSourceHandler',
                    'description' => 'Спортивные организации г. Нефтеюганск',
                    'need_update' => 0,
                    'is_active' => 1,
                    'current_hash' => null,
                    'last_update' => null,
                    'dataset_type_id' => 1,
                    'municipality_id' => 19,
                ],
            53 =>
                [
                    'id' => 54,
                    'url' => 'https://data.admhmao.ru/api/data/?id=8690356',
                    'data_type' => 'json',
                    'class_handler' => 'Modules\\SportSectionsWidget\\OpenDataHandlers\\Trainers\\NefteuganskSourceHandler',
                    'description' => 'Спортивные тренеры г. Нефтеюганск',
                    'need_update' => 0,
                    'is_active' => 1,
                    'current_hash' => null,
                    'last_update' => null,
                    'dataset_type_id' => 2,
                    'municipality_id' => 19,
                ],
            54 =>
                [
                    'id' => 55,
                    'url' => 'https://data.admhmao.ru/api/data/?id=4401398',
                    'data_type' => 'json',
                    'class_handler' => 'Modules\\SportSectionsWidget\\OpenDataHandlers\\Sections\\NefteuganskSourceHandler',
                    'description' => 'Спортивные секции г. Нефтеюганск',
                    'need_update' => 0,
                    'is_active' => 1,
                    'current_hash' => null,
                    'last_update' => null,
                    'dataset_type_id' => 3,
                    'municipality_id' => 19,
                ],
            55 =>
                [
                    'id' => 56,
                    'url' => 'https://data.admhmao.ru/api/data/?id=3588615',
                    'data_type' => 'json',
                    'class_handler' => 'Modules\\SportSectionsWidget\\OpenDataHandlers\\OrganisationsSourceHandler',
                    'description' => 'Спортивные организации г. Когалым',
                    'need_update' => 0,
                    'is_active' => 1,
                    'current_hash' => null,
                    'last_update' => null,
                    'dataset_type_id' => 1,
                    'municipality_id' => 20,
                ],
            56 =>
                [
                    'id' => 57,
                    'url' => 'https://data.admhmao.ru/api/data/?id=3506898',
                    'data_type' => 'json',
                    'class_handler' => 'Modules\\SportSectionsWidget\\OpenDataHandlers\\Trainers\\KogalymSourceHandler',
                    'description' => 'Спортивные тренеры г. Когалым',
                    'need_update' => 0,
                    'is_active' => 1,
                    'current_hash' => null,
                    'last_update' => null,
                    'dataset_type_id' => 2,
                    'municipality_id' => 20,
                ],
            57 =>
                [
                    'id' => 58,
                    'url' => 'https://data.admhmao.ru/api/data/?id=3506875',
                    'data_type' => 'json',
                    'class_handler' => 'Modules\\SportSectionsWidget\\OpenDataHandlers\\SectionsSourceHandler',
                    'description' => 'Спортивные секции г. Когалым',
                    'need_update' => 0,
                    'is_active' => 1,
                    'current_hash' => null,
                    'last_update' => null,
                    'dataset_type_id' => 3,
                    'municipality_id' => 20,
                ],
            58 =>
                [
                    'id' => 59,
                    'url' => 'https://data.admhmao.ru/api/data/?id=7558286',
                    'data_type' => 'json',
                    'class_handler' => 'Modules\\SportSectionsWidget\\OpenDataHandlers\\OrganisationsSourceHandler',
                    'description' => 'Спортивные организации Нефтеюганского района',
                    'need_update' => 0,
                    'is_active' => 1,
                    'current_hash' => null,
                    'last_update' => null,
                    'dataset_type_id' => 1,
                    'municipality_id' => 21,
                ],
            59 =>
                [
                    'id' => 60,
                    'url' => 'https://data.admhmao.ru/api/data/?id=4095655',
                    'data_type' => 'json',
                    'class_handler' => 'Modules\\SportSectionsWidget\\OpenDataHandlers\\Trainers\\NefteuganskDistrictSourceHandler',
                    'description' => 'Спортивные тренеры Нефтеюганского района',
                    'need_update' => 0,
                    'is_active' => 1,
                    'current_hash' => null,
                    'last_update' => null,
                    'dataset_type_id' => 2,
                    'municipality_id' => 21,
                ],
            60 =>
                [
                    'id' => 61,
                    'url' => 'https://data.admhmao.ru/api/data/?id=4095305',
                    'data_type' => 'json',
                    'class_handler' => 'Modules\\SportSectionsWidget\\OpenDataHandlers\\SectionsSourceHandler',
                    'description' => 'Спортивные секции Нефтеюганского района',
                    'need_update' => 0,
                    'is_active' => 1,
                    'current_hash' => null,
                    'last_update' => null,
                    'dataset_type_id' => 3,
                    'municipality_id' => 21,
                ],
            61 =>
                [
                    'id' => 62,
                    'url' => 'https://data.admhmao.ru/api/data/?id=8262031',
                    'data_type' => 'json',
                    'class_handler' => 'Modules\\SportSectionsWidget\\OpenDataHandlers\\Organisations\\NyaganSourceHandler',
                    'description' => 'Спортивные организации г. Нягань',
                    'need_update' => 0,
                    'is_active' => 1,
                    'current_hash' => null,
                    'last_update' => null,
                    'dataset_type_id' => 1,
                    'municipality_id' => 22,
                ],
            62 =>
                [
                    'id' => 63,
                    'url' => 'https://data.admhmao.ru/api/data/?id=8262048',
                    'data_type' => 'json',
                    'class_handler' => 'Modules\\SportSectionsWidget\\OpenDataHandlers\\Trainers\\NyaganSourceHandler',
                    'description' => 'Спортивные секции и тренеры с расписанием г. Нягань',
                    'need_update' => 0,
                    'is_active' => 1,
                    'current_hash' => null,
                    'last_update' => null,
                    'dataset_type_id' => 2,
                    'municipality_id' => 22,
                ],

        );
        foreach ($data as $row) {
            if (DB::table('sport_sections_widget_od_datasets')->where('id', $row['id'])->doesntExist()) {

                DB::table('sport_sections_widget_od_datasets')->insert($row);
            }
        }
    }
}
