/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
    export interface GlobalComponents {
        ElButton: typeof import('element-plus/es')['ElButton']
        ElCard: typeof import('element-plus/es')['ElCard']
        ElCollapse: typeof import('element-plus/es')['ElCollapse']
        ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
        ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
        ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
        ElDialog: typeof import('element-plus/es')['ElDialog']
        ElForm: typeof import('element-plus/es')['ElForm']
        ElFormItem: typeof import('element-plus/es')['ElFormItem']
        ElInput: typeof import('element-plus/es')['ElInput']
        ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
        ElOption: typeof import('element-plus/es')['ElOption']
        ElSelect: typeof import('element-plus/es')['ElSelect']
        RouterLink: typeof import('vue-router')['RouterLink']
        RouterView: typeof import('vue-router')['RouterView']
    }

    export interface ComponentCustomProperties {
        vLoading: typeof import('element-plus/es')['ElLoadingDirective']
    }
}
