[program:laravel-horizon]
process_name=%(program_name)s_%(process_num)02d
user=laradock
command=php /var/www/artisan horizon
autostart=true
autorestart=true
redirect_stderr=true
stderr_logfile=/dev/stdout
stdout_logfile_maxbytes=0 # Если в будущем будет два процесса, то чтобы они не мешали друг другу - надо ставить 0 https://supervisord.org/configuration.html
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
